# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Generate prebuilts and publish

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "1 1 * * *"


jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # full history so we can switch branches

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Build
      run: | 
        cd whatsfly/dependencies
        cp go.mod go.mod.save
        cp go.sum go.sum.save
        go get -u
        go mod tidy
        GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -buildmode=c-shared -ldflags=-s -o ../../whatsmeow-linux-amd64.so ./main.go
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -buildmode=c-shared -ldflags=-s -o ../../whatsmeow-windows-amd64.dll ./main.go
        rm go.mod
        rm go.sum
        cp go.mod.save go.mod 
        cp go.sum.save go.sum 

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        
        git checkout prebuilts
        

        
        mkdir -p linux-amd64-$GITHUB_REF_NAME
        mv whatsmeow-linux-amd64.so linux-amd64-$GITHUB_REF_NAME/linux-amd64-$GITHUB_SHA.so


        rm -f linux-amd64-$GITHUB_REF_NAME/latest.so
        ln -s linux-amd64-$GITHUB_REF_NAME/latest.so linux-amd64-$GITHUB_REF_NAME/linux-amd64-$GITHUB_SHA.so
        git add linux-amd64-$GITHUB_REF_NAME/linux-amd64-$GITHUB_SHA.so
        git add linux-amd64-$GITHUB_REF_NAME/latest.so
        

        
        mkdir -p windows-amd64-$GITHUB_REF_NAME
        mv whatsmeow-windows-amd64.dll windows-amd64-$GITHUB_REF_NAME/windows-amd64-$GITHUB_SHA.dll

        rm -f windows-amd64-$GITHUB_REF_NAME/latest.dll
        ln -s windows-amd64-$GITHUB_REF_NAME/latest.dll windows-amd64-$GITHUB_REF_NAME/linux-amd64-$GITHUB_SHA.dll
        git add windows-amd64-$GITHUB_REF_NAME/windows-amd64-$GITHUB_SHA.dll
        git add windows-amd64-$GITHUB_REF_NAME/latest.dll
        
          
        git commit -m "Push prebuilts" || echo "No changes to commit"

    - name: Push to prebuilts branch
      run: |
        git push origin prebuilts

  # build-windows:
  #   runs-on: windows-latest
  #   needs: build-ubuntu
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0  # full history so we can switch branches

  #   - name: Set up Go
  #     uses: actions/setup-go@v4
  #     with:
  #       go-version: '1.24'

  #   - name: Build
  #     env:
  #       GOOS: windows
  #       GOARCH: amd64
  #       CGO_ENABLED: 1
  #       CC: x86_64-w64-mingw32-gcc
  #     run: |
  #         cd whatsfly/dependencies
  #         cp go.mod go.mod.save
  #         cp go.sum go.sum.save
  #         go get -u
  #         go mod tidy
  #         go build -v -buildmode=c-shared -ldflags=-s -o ../../whatsmeow-windows-amd64.dll ./main.go
  #         rm go.mod
  #         rm go.sum
  #         cp go.mod.save go.mod 
  #         cp go.sum.save go.sum 
        
  #   - name: Commit changes
  #     run: |
  #       git config user.name "github-actions[bot]"
  #       git config user.email "github-actions[bot]@users.noreply.github.com"

        
  #       git checkout prebuilts
        

  #       mv whatsmeow-windows-amd64.dll windows-amd64-$env:GITHUB_SHA.dll
  #       echo $env:GITHUB_SHA >> windows-amd64-$env:GITHUB_REF_NAME

  #       git add windows-amd64-$env:GITHUB_SHA.dll
  #       git add windows-amd64-$env:GITHUB_REF_NAME
          
  #       git commit -m "Push prebuilts" || echo "No changes to commit"

  #   - name: Push to prebuilts branch
  #     run: |
  #       git push origin prebuilts
  build-osx:
    runs-on: macos-latest
    needs: build-ubuntu
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # full history so we can switch branches

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      env:
        CGO_ENABLED: 1
      run: |
          cd whatsfly/dependencies
          cp go.mod go.mod.save
          cp go.sum go.sum.save
          go get -u
          go mod tidy
          GOOS=darwin GOARCH=amd64 go build -v -buildmode=c-shared -o ../../whatsmeow-darwin-amd64.dylib ./main.go
          GOOS=darwin GOARCH=arm64 go build -v -buildmode=c-shared -o ../../whatsmeow-darwin-arm64.dylib ./main.go
          rm go.mod
          rm go.sum
          cp go.mod.save go.mod 
          cp go.sum.save go.sum 
    
    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        
        git checkout prebuilts
        

        
        mkdir -p darwin-amd64-$GITHUB_REF_NAME
        mv whatsmeow-darwin-amd64.dylib darwin-amd64-$GITHUB_REF_NAME/darwin-amd64-$GITHUB_SHA.dylib


        rm -f darwin-amd64-$GITHUB_REF_NAME/latest.dylib
        ln -s darwin-amd64-$GITHUB_REF_NAME/latest.dylib darwin-amd64-$GITHUB_REF_NAME/darwin-amd64-$GITHUB_SHA.dylib
        git add darwin-amd64-$GITHUB_REF_NAME/darwin-amd64-$GITHUB_SHA.dylib
        git add darwin-amd64-$GITHUB_REF_NAME/latest.dylib

        

        
        mkdir -p darwin-arm64-$GITHUB_REF_NAME
        mv whatsmeow-darwin-arm64.dylib darwin-arm64-$GITHUB_REF_NAME/darwin-arm64-$GITHUB_SHA.dylib

        rm -f darwin-arm64-$GITHUB_REF_NAME/latest.dylib
        ln -s darwin-arm64-$GITHUB_REF_NAME/latest.dylib darwin-arm64-$GITHUB_REF_NAME/darwin-arm64-$GITHUB_SHA.dylib
        git add darwin-arm64-$GITHUB_REF_NAME/darwin-arm64-$GITHUB_SHA.dylib
        git add darwin-arm64-$GITHUB_REF_NAME/latest.dylib
        
          
        git commit -m "Push prebuilts" || echo "No changes to commit"

    - name: Push to prebuilts branch
      run: |
        git push origin prebuilts